import React, { Component } from 'react';
import '../../../../../assests/css/custom.css'

import '../../../../../assests/css/custom.min.css'

class analyticsComponent extends Component {
    constructor(props) {
        super(props);
        this.state = {

        }

    }
    render() {
        return (
            <div>
<div class="right_col" role="main" style={{marginLeft:'0px'}}>
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Analytics </h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for..."/>
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Analytics </h2>
   
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                     <div class="col-xs-2">
                      <ul class="nav nav-tabs tabs-left">
                        <li class="active"><a href="#analytics-settings" data-toggle="tab">Analytics Settings</a>
                        </li>
                        <li><a href="#analytics-models" data-toggle="tab">Analytics Models</a>
                        </li>
        
                      </ul>
                    </div>

                    <div class="col-xs-10">
                      <div class="tab-content">
                        <div class="tab-pane active" id="analytics-settings">
                          <p class="lead">Analytics settings</p>
                          <fieldset id="yui_3_17_2_1_1516078376036_47">
<div class="clearer"></div>
<div class="form-item row" id="admin-predictionsprocessor">
    <div class="form-label col-sm-3 text-sm-right" id="yui_3_17_2_1_1516078376036_46">
        <label for="id_s_analytics_predictionsprocessor" id="yui_3_17_2_1_1516078376036_45">
            Predictions processor
        </label>
        <span class="form-shortname d-block small text-muted">analytics | predictionsprocessor</span>
    </div>
    <div class="form-setting col-sm-9" id="yui_3_17_2_1_1516078376036_58">
        <div class="form-select defaultsnext" id="yui_3_17_2_1_1516078376036_57">
    <select id="id_s_analytics_predictionsprocessor" name="s_analytics_predictionsprocessor" class="custom-select">
            <option value="\mlbackend_php\processor" selected="">PHP machine learning backend</option>
            <option value="\mlbackend_python\processor">Python machine learning backend</option>
    </select>
</div>
            <div class="form-defaultinfo text-muted ">Default: PHP machine learning backend</div>
        <div class="form-description m-t-1"><p>A predictions processor is the machine-learning backend that processes the datasets generated by calculating models' indicators and targets. All trained algorithms and predictions will be deleted if you change to another predictions processor.</p>
</div>
    </div>
</div><div class="form-item row" id="admin-logstore">
    <div class="form-label col-sm-3 text-sm-right">
        <label for="id_s_analytics_logstore">
            Log store used for analytics
        </label>
        <span class="form-shortname d-block small text-muted">analytics | logstore</span>
    </div>
    <div class="form-setting col-sm-9">
        <div class="form-select defaultsnext">
    <select id="id_s_analytics_logstore" name="s_analytics_logstore" class="custom-select">
            <option value="logstore_standard" selected="">Standard log</option>
    </select>
</div>
            <div class="form-defaultinfo text-muted ">Default: Standard log</div>
        <div class="form-description m-t-1"><p>The log store that will be used by the analytics API to read users' activity</p>
</div>
    </div>
</div><div class="form-item row" id="admin-timesplittings">
    <div class="form-label col-sm-3 text-sm-right">
        <label for="id_s_analytics_timesplittings">
            Time splitting methods
        </label>
        <span class="form-shortname d-block small text-muted">analytics | timesplittings</span>
    </div>
    <div class="form-setting col-sm-9">
        <div class="form-select">
    <input type="hidden" name="s_analytics_timesplittings[xxxxx]" value="1"/>
    <select id="id_s_analytics_timesplittings" name="s_analytics_timesplittings[]" size="6" class="form-control" multiple="">
            <option value="\core\analytics\time_splitting\deciles">Tenths</option>
            <option value="\core\analytics\time_splitting\deciles_accum">Tenths accumulative</option>
            <option value="\core\analytics\time_splitting\no_splitting">No time splitting</option>
            <option value="\core\analytics\time_splitting\quarters" selected="">Quarters</option>
            <option value="\core\analytics\time_splitting\quarters_accum" selected="">Quarters accumulative</option>
            <option value="\core\analytics\time_splitting\single_range" selected="">Single range</option>
    </select>
</div>
            <div class="form-defaultinfo text-muted ">Default: Quarters, Quarters accumulative, Single range</div>
        <div class="form-description m-t-1"><p>The time-splitting method divides the course duration into parts; the predictions engine will run at the end of these parts. It is recommended that you only enable the time-splitting methods you may be interested in using. The evaluation process will iterate through all enabled time-spitting methods, so the more time-splitting methods enabled, the slower the evaluation process will be.</p>
</div>
    </div>
</div><div class="form-item row" id="admin-modeloutputdir">
    <div class="form-label col-sm-3 text-sm-right">
        <label for="id_s_analytics_modeloutputdir">
            Models output directory
        </label>
        <span class="form-shortname d-block small text-muted">analytics | modeloutputdir</span>
    </div>
    <div class="form-setting col-sm-9">
        <div class="form-file defaultsnext">
    <div class="form-inline">
        <input type="text" name="s_analytics_modeloutputdir" id="id_s_analytics_modeloutputdir" size="50" value="/var/moodledata/models" class="form-control text-ltr"/>
                <span class="text-success">✔</span>
    </div>
</div>
            <div class="form-defaultinfo text-muted text-ltr">Default: /var/moodledata/models</div>
        <div class="form-description m-t-1"><p>Directory where prediction processors store all evaluation info. Useful for debugging and research.</p>
</div>
    </div>
</div><div class="form-item row" id="admin-onlycli">
    <div class="form-label col-sm-3 text-sm-right">
        <label for="id_s_analytics_onlycli">
            Analytics processes execution via command line only
        </label>
        <span class="form-shortname d-block small text-muted">analytics | onlycli</span>
    </div>
    <div class="form-setting col-sm-9">
        <div class="form-checkbox defaultsnext">
    <input type="hidden" name="s_analytics_onlycli" value="0"/>
    <input type="checkbox" name="s_analytics_onlycli" value="1" id="id_s_analytics_onlycli" checked=""/>
</div>
            <div class="form-defaultinfo text-muted ">Default: Yes</div>
        <div class="form-description m-t-1"><p>Analytics processes like evaluating models, training machine learning algorithms or getting predictions can take some time, they will run as cron tasks and they can be forced via command line. Disable this setting if you want your site managers to be able to run these processes manually via web interface</p>
</div>
    </div>
</div><div class="form-item row" id="admin-modeltimelimit">
    <div class="form-label col-sm-3 text-sm-right">
        <label for="id_s_analytics_modeltimelimitv">
            Analysis time limit per model
        </label>
        <span class="form-shortname d-block small text-muted">analytics | modeltimelimit</span>
    </div>
    <div class="form-setting col-sm-9">
        <div class="form-duration defaultsnext">
    <div class="form-inline">
        <input type="text" size="5" id="id_s_analytics_modeltimelimitv" name="s_analytics_modeltimelimit[v]" value="20" class="form-control text-ltr"/>
        <label class="sr-only" for="id_s_analytics_modeltimelimitu">duration units</label>
        <select id="id_s_analytics_modeltimelimitu" name="s_analytics_modeltimelimit[u]" class="form-control">
                <option value="604800">weeks</option>
                <option value="86400">days</option>
                <option value="3600">hours</option>
                <option value="60" selected="">minutes</option>
                <option value="1">seconds</option>
        </select>
    </div>
</div>
            <div class="form-defaultinfo text-muted ">Default: 20 minutes</div>
        <div class="form-description m-t-1"><p>This setting limits the time each model spends analysing the site contents.</p>
</div>
    </div>
</div></fieldset>

<div class="row">
                <div class="col-md-offset-3 col-md-3">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
                        </div>
                        <div class="tab-pane" id="analytics-models">
                          <p class="lead">Analytics models</p>
                          <div class="alert alert-info alert-block fade in ">
        <button type="button" class="close" data-dismiss="alert">×</button>
        A scheduled task iterates through enabled models and gets predictions. Models evaluation via the web interface is disabled. You can allow these processes to be executed manually via the web interface by disabling the <a href="http://35.169.62.69/admin/settings.php?section=analyticssettings#id_s_analytics_onlycli">'onlycli'</a> analytics setting.
    </div>
    <table class="table table-striped" id="yui_3_17_2_1_1516078382814_20">
        <caption id="yui_3_17_2_1_1516078382814_19">Analytics models</caption>
        <thead id="yui_3_17_2_1_1516078382814_26">
            <tr id="yui_3_17_2_1_1516078382814_25">
                <th scope="col" id="yui_3_17_2_1_1516078382814_24">Target</th>
                <th scope="col">Enabled</th>
                <th scope="col">Indicators</th>
                <th scope="col">Time splitting</th>
                <th scope="col">Insights</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <span class="target-name">No teaching</span>
                        <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This target describes whether courses due to start in the coming week will have teaching activity.</p></div> " data-html="true" tabindex="0" data-trigger="focus">
                          <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with No teaching" aria-label="Help with No teaching"></i>
                        </a>
                </td>
                <td>
                        <i class="icon fa fa-check fa-fw " aria-hidden="true" title="Yes" aria-label="Yes"></i>
                </td>
                <td>
                    <ul>
                        <li>
                            There are no teachers
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator reflects that this course has no teachers.</p></div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with There are no teachers" aria-label="Help with There are no teachers"></i>
                                </a>
                        </li>
                        <li>
                            There are no students
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator reflects that this course has no students.</p></div>"  data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with There are no students" aria-label="Help with There are no students"></i>
                                </a>
                        </li>
                    </ul>
                </td>
                <td>
                        Single range
                            <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This time-splitting method considers the entire course as a single span.</p></div> " data-html="true" tabindex="0" data-trigger="focus">
                              <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Single range" aria-label="Help with Single range"></i>
                            </a>
                </td>
                <td>
                        No predictions available yet
                </td>
                <td>
                        <div class="action-menu moodle-actionmenu" id="action-menu-3" data-enhance="moodle-core-actionmenu" data-owner="model-actions-2">
                        
                                <div class="menubar" id="action-menu-3-menubar" role="menubar">
                        
                                    <div class="dropdown d-inline">
    <a href="#" class="dropdown-toggle" id="dropdown-3" title="" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Actions <b class="caret"></b></a>
        <div class="dropdown-menu dropdown-menu-right menu  align-tl-bl" id="action-menu-3-menu" data-rel="menu-content" aria-labelledby="action-menu-toggle-3" role="menu" data-align="tl-bl">
            <a href="model.php?id=2&amp;sesskey=HkeD79OOU9&amp;action=disable" class="dropdown-item menu-action" role="menuitem" aria-labelledby="actionmenuaction-8"><i class="icon fa fa-ban fa-fw " aria-hidden="true" title="Disable" aria-label="Disable"></i><span class="menu-action-text" id="actionmenuaction-8">Disable</span></a>
        </div>
</div>

                        
                                </div>
                        
                        </div>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="target-name">Students at risk of dropping out</span>
                        <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This target describes whether the student is considered at risk of dropping out.</p></div> " data-html="true" tabindex="0" data-trigger="focus">
                          <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Students at risk of dropping out" aria-label="Help with Students at risk of dropping out"></i>
                        </a>
                </td>
                <td>
                        No
                </td>
                <td>
                    <ul>
                        <li>
                            Assignment cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in an Assignment activity.</p></div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Assignment cognitive" aria-label="Help with Assignment cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Assignment social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in an Assignment activity.</p></div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Assignment social" aria-label="Help with Assignment social"></i>
                                </a>
                        </li>
                        <li>
                            Book cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Book resource.</p></div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Book cognitive" aria-label="Help with Book cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Book social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Book resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Book social" aria-label="Help with Book social"></i>
                                </a>
                        </li>
                        <li>
                            Chat cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Chat activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Chat cognitive" aria-label="Help with Chat cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Chat social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Chat activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Chat social" aria-label="Help with Chat social"></i>
                                </a>
                        </li>
                        <li>
                            Choice cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Choice activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Choice cognitive" aria-label="Help with Choice cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Choice social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Choice activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Choice social" aria-label="Help with Choice social"></i>
                                </a>
                        </li>
                        <li>
                            Database cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Database activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Database cognitive" aria-label="Help with Database cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Database social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Database activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Database social" aria-label="Help with Database social"></i>
                                </a>
                        </li>
                        <li>
                            Feedback cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Feedback activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Feedback cognitive" aria-label="Help with Feedback cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Feedback social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Feedback activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Feedback social" aria-label="Help with Feedback social"></i>
                                </a>
                        </li>
                        <li>
                            Folder cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Folder resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Folder cognitive" aria-label="Help with Folder cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Folder social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Folder resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Folder social" aria-label="Help with Folder social"></i>
                                </a>
                        </li>
                        <li>
                            Forum cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Forum activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Forum cognitive" aria-label="Help with Forum cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Forum social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Forum activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Forum social" aria-label="Help with Forum social"></i>
                                </a>
                        </li>
                        <li>
                            Glossary cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Glossary activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Glossary cognitive" aria-label="Help with Glossary cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Glossary social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Glossary activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Glossary social" aria-label="Help with Glossary social"></i>
                                </a>
                        </li>
                        <li>
                            IMS pkg cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in an IMS content package resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with IMS pkg cognitive" aria-label="Help with IMS pkg cognitive"></i>
                                </a>
                        </li>
                        <li>
                            IMS pkg social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in an IMS content package resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with IMS pkg social" aria-label="Help with IMS pkg social"></i>
                                </a>
                        </li>
                        <li>
                            Label cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Label resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Label cognitive" aria-label="Help with Label cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Label social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Label resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Label social" aria-label="Help with Label social"></i>
                                </a>
                        </li>
                        <li>
                            Lesson cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Lesson activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Lesson cognitive" aria-label="Help with Lesson cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Lesson social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Lesson activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Lesson social" aria-label="Help with Lesson social"></i>
                                </a>
                        </li>
                        <li>
                            LTI cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in an LTI activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with LTI cognitive" aria-label="Help with LTI cognitive"></i>
                                </a>
                        </li>
                        <li>
                            LTI social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in an LTI activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with LTI social" aria-label="Help with LTI social"></i>
                                </a>
                        </li>
                        <li>
                            Page cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Page resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Page cognitive" aria-label="Help with Page cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Page social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Page resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Page social" aria-label="Help with Page social"></i>
                                </a>
                        </li>
                        <li>
                            Quiz cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Quiz activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Quiz cognitive" aria-label="Help with Quiz cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Quiz social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Quiz activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Quiz social" aria-label="Help with Quiz social"></i>
                                </a>
                        </li>
                        <li>
                            File cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a File resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with File cognitive" aria-label="Help with File cognitive"></i>
                                </a>
                        </li>
                        <li>
                            File social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a File resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with File social" aria-label="Help with File social"></i>
                                </a>
                        </li>
                        <li>
                            SCORM cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a SCORM activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with SCORM cognitive" aria-label="Help with SCORM cognitive"></i>
                                </a>
                        </li>
                        <li>
                            SCORM social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a SCORM activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with SCORM social" aria-label="Help with SCORM social"></i>
                                </a>
                        </li>
                        <li>
                            Survey cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Survey activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Survey cognitive" aria-label="Help with Survey cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Survey social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Survey activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Survey social" aria-label="Help with Survey social"></i>
                                </a>
                        </li>
                        <li>
                            URL cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a URL resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with URL cognitive" aria-label="Help with URL cognitive"></i>
                                </a>
                        </li>
                        <li>
                            URL social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a URL resource.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with URL social" aria-label="Help with URL social"></i>
                                </a>
                        </li>
                        <li>
                            Wiki cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Wiki activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Wiki cognitive" aria-label="Help with Wiki cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Wiki social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Wiki activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Wiki social" aria-label="Help with Wiki social"></i>
                                </a>
                        </li>
                        <li>
                            Workshop cognitive
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the cognitive depth reached by the student in a Workshop activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Workshop cognitive" aria-label="Help with Workshop cognitive"></i>
                                </a>
                        </li>
                        <li>
                            Workshop social
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the social breadth reached by the student in a Workshop activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Workshop social" aria-label="Help with Workshop social"></i>
                                </a>
                        </li>
                        <li>
                            Completion tracking enabled
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator represents that completion tracking has been enabled for this course.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Completion tracking enabled" aria-label="Help with Completion tracking enabled"></i>
                                </a>
                        </li>
                        <li>
                            Course potential cognitive depth
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the potential cognitive depth that could be reached by a student participating in course activities.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Course potential cognitive depth" aria-label="Help with Course potential cognitive depth"></i>
                                </a>
                        </li>
                        <li>
                            Course potential social breadth
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator is based on the potential social breadth that could be reached by the student participating in course activities.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Course potential social breadth" aria-label="Help with Course potential social breadth"></i>
                                </a>
                        </li>
                        <li>
                            Course accessed after end date
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator reflects if the student accessed the course after the course end date.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Course accessed after end date" aria-label="Help with Course accessed after end date"></i>
                                </a>
                        </li>
                        <li>
                            Course accessed before start date
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator reflects if the student accessed the course before the course start date.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Course accessed before start date" aria-label="Help with Course accessed before start date"></i>
                                </a>
                        </li>
                        <li>
                            Any write action in the course
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator represents any write (submit) action taken by the student in any course activity.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Any write action in the course" aria-label="Help with Any write action in the course"></i>
                                </a>
                        </li>
                        <li>
                            Read actions amount
                                <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>This indicator represents the number of read (view) actions taken by the student.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                                  <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Read actions amount" aria-label="Help with Read actions amount"></i>
                                </a>
                        </li>
                    </ul>
                </td>
                <td>
                        Not yet defined
                            <a class="btn btn-link p-a-0" role="button" data-container="body" data-toggle="popover" data-placement="right" data-content="<div class=&quot;no-overflow&quot;><p>You need to select a time-splitting method before enabling the model.</p>
</div> " data-html="true" tabindex="0" data-trigger="focus">
                              <i class="icon fa fa-question-circle text-info fa-fw " aria-hidden="true" title="Help with Time splitting is not defined" aria-label="Help with Time splitting is not defined"></i>
                            </a>
                </td>
                <td>
                        Disabled model
                </td>
                <td>
                        <div class="action-menu moodle-actionmenu" id="action-menu-4" data-enhance="moodle-core-actionmenu" data-owner="model-actions-1">
                        
                                <div class="menubar" id="action-menu-4-menubar" role="menubar">
                        
                                    <div class="dropdown d-inline">
    <a href="#" class="dropdown-toggle" id="dropdown-4" title="" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions<b class="caret"></b></a>
        <div class="dropdown-menu dropdown-menu-right menu  align-tl-bl" id="action-menu-4-menu" data-rel="menu-content" aria-labelledby="action-menu-toggle-4" role="menu" data-align="tl-bl">
            <a href="model.php?id=1&amp;sesskey=HkeD79OOU9&amp;action=log" class="dropdown-item menu-action" role="menuitem" aria-labelledby="actionmenuaction-9"><i class="icon fa fa-area-chart fa-fw " aria-hidden="true" title="Log" aria-label="Log"></i><span class="menu-action-text" id="actionmenuaction-9">Log</span></a><a href="model.php?id=1&amp;sesskey=HkeD79OOU9&amp;action=edit" class="dropdown-item menu-action" role="menuitem" aria-labelledby="actionmenuaction-10"><i class="icon fa fa-cog fa-fw " aria-hidden="true" title="Edit" aria-label="Edit"></i><span class="menu-action-text" id="actionmenuaction-10">Edit</span></a><a href="model.php?id=1&amp;sesskey=HkeD79OOU9&amp;action=invalidanalysables" class="dropdown-item menu-action" role="menuitem" aria-labelledby="actionmenuaction-11"><i class="icon fa fa-area-chart fa-fw " aria-hidden="true" title="Invalid site elements" aria-label="Invalid site elements"></i><span class="menu-action-text" id="actionmenuaction-11">Invalid site elements</span></a>
        </div>
</div>

                        
                                </div>
                        
                        </div>
                </td>
            </tr>
        </tbody>
    </table>

                        </div>
          
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
            </div>

        );
    }
}

export default analyticsComponent;
